### PR TITLE
1559

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/230)

### CODE REVIEW

**Review by Pana — CHANGES_REQUESTED** [review]
the cfx_getParamsFromVote response has added one more field

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/230#-:-NzfMHnq9k7oxlg4XOWB:b87ndgg)* status: all files reviewed, 5 unresolved discussions (waiting on @wangdayong228 and @wanliqun)

___
*[`client.go` line 941 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/230#-NzfJaax3byaC1-2YWb8:-NzfJaax3byaC1-2YWb9:b-b537lw) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/4a285c33346fc5d3604a64c8a4400cfdee3ddcfc/client.go#L941)):*
> ```Go
> 	}
> 
> 	data.maxPriorityFeePerGas = types.NewBigInt(1.5e9)
> ```

seems maxPriorityFeePerGas should come from cfx_maxPriorityFeePerGas or feeHistory
___
*[`client_test.go` line 97 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/230#-NzfLJbw9lNM0E2A-C_R:-NzfLJbw9lNM0E2A-C_S:biue68m) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/4a285c33346fc5d3604a64c8a4400cfdee3ddcfc/client_test.go#L97)):*
> ```Go
> 
> // func TestClientHookCallContext(t *testing.T) {
> // 	c := MustNewClient("https://test.confluxrpc.com")
> ```

why these lines are commented ?
___
*[`interface.go` line 119 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/230#-NzfGxk0C8Y59rtDFR8e:-NzfGxk0C8Y59rtDFR8f:bv60nsl) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/4a285c33346fc5d3604a64c8a4400cfdee3ddcfc/interface.go#L119)):*
> ```Go
> 	GetPoSRewardByEpoch(epoch types.Epoch) (reward *postypes.EpochReward, err error)
> 	GetFeeHistory(blockCount hexutil.Uint64, lastEpoch types.Epoch, rewardPercentiles []float64) (feeHistory *types.FeeHistory, err error)
> 	GetMaxPriorityFeePerGas() (maxPriorityFeePerGas *hexutil.Big, err error)
> ```

missing new added cfx_getFeeBurnt method
___
*[`types/block_test.go` line 48 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/230#-NzfLYG81VL4vPO--e7R:-NzfLYG81VL4vPO--e7S:b-3gkbcp) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/4a285c33346fc5d3604a64c8a4400cfdee3ddcfc/types/block_test.go#L48)):*
> ```Go
> 
> func TestRLPMarshalBlock(t *testing.T) {
> 	testJsonStr1 := `{"hash":"0xa6528367a9287ed3a66fc64457db15e2aaa93104a3fd06d4f0a2beb6cc1f26c8","parentHash":"0x5aef321e4e49f430ad6322af8a0133eae83e635f7893c996eb127dcf24a00b14","height":"0x792776","miner":"cfx:aatxetsp0kdarpdb5stdyex11dr3x6sb0jw2gykec0","deferredStateRoot":"0xa979a8c492c44a512aa9529911a7862e1b61ce2aa441645e865def9219d2c68b","deferredReceiptsRoot":"0xd5f7e7960e9b56753868260c280746c01353dcd1b91a20cee2c919d0dc7bf78b","deferredLogsBloomHash":"0xd397b3b043d87fcd6fad1291ff0bfd16401c274896d8c63a923727f077b8e0b5","blame":"0x0","transactionsRoot":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470","epochNumber":"0x792778","blockNumber":"0xf7cf1c","gasLimit":"0x1c9c380","gasUsed":"0x0","timestamp":"0x6026478e","difficulty":"0xa8b175a4dc","powQuality":"0x2223e36adc5","refereeHashes":["0x4e4fca2593068b1dc83ecae3c1eaf0e4d41623985fd03d7f15fc1d63f653e7d2"],"adaptive":false,"nonce":"0x209fc5fbe719dace","size":"0x0","custom":[],"posReference":null,"transactions":[]}`
> ```

It's better more these test data into json file with formatted content, so it's easy to read 
___
*[`types/transaction.go` line 40 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/230#-NzfHeAwC4SF4rGcsNVM:-NzfHeAwC4SF4rGcsNVN:b-f92ztn) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/4a285c33346fc5d3604a64c8a4400cfdee3ddcfc/types/transaction.go#L40)):*
> ```Go
> 	Status           *hexutil.Uint64 `json:"status"`
> 
> 	AccessList           *etypes.AccessList `json:"accessList,omitempty"`
> ```

this should be CfxAccessList right ?

**Review by Pana — COMMENTED** [review]
Remember add the changes note to changelog

> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/230#-:-NzfMZR-AxsZeVwBCot8:b-ijft7g)* status: all files reviewed, 5 unresolved discussions (waiting on @wangdayong228 and @wanliqun)

**Review by wanliqun — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/230)* status: all files reviewed, 7 unresolved discussions (waiting on @wangdayong228)

___
*[`client.go` line 736 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/230#-NzfMjiI6HK4wjYntmXJ:-NzfMjiI6HK4wjYntmXK:bs1clnz) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/4a285c33346fc5d3604a64c8a4400cfdee3ddcfc/client.go#L736)):*
> ```Go
> }
> 
> // GetPosRewardByEpoch returns pos rewarded in this epoch
> ```

Incorrect comment.
___
*[`client.go` line 922 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/230#-NzfPiaB4bHQ45ss7h0e:-NzfPiaB4bHQ45ss7h0f:b-pyf4ct) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/4a285c33346fc5d3604a64c8a4400cfdee3ddcfc/client.go#L922)):*
> ```Go
> }
> 
> func (client *Client) getFeeData() (*gasFeeData, error) {
> ```

I suggest getting this fee data as compact as possible from the perspective of performance. eg., if we are using legacy txn, why bother calculating `baseFee` or `majorityFee` since it takes an extra two round trips?

**Review by wanliqun — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/230)* status: all files reviewed, 5 unresolved discussions (waiting on @wangdayong228)

**Review by Pana — DISMISSED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/230)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wangdayong228)

**Pull request merged**
