### PR TITLE
Fix bugs

### PR DESCRIPTION
**Pull request by wangdayong228**
1. add rpc GetAccountPendingTransactions
    2. update readme.md
    3. remove wrapped msg of callrpc
    4. set client request default timeout to 30s

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/82)

### CODE REVIEW

**Review by Pana — COMMENTED** [review]
The new RPC method should also been added to the Interface

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/82#-:-MbeTJ9eEG5g82bbFzZ3:bhiz625)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @boqiu)

**Review by Pana — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/82#-:-MbeTR9L-Qx9ucq5wdDk:bnfp4nl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @boqiu)

**Review by Pana — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/82)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @boqiu)

**Review by boqiu — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/82#-:-MbeZo1k5FieF_p65A-r:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @wangdayong228)

___
*[types/transaction.go, line 190 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/82#-MbeZNcI5fEry1Nstc_V:-MbeZNcI5fEry1Nstc_W:b-iw6ndp) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/11c9d54265b674b85f3fc241ffb92f2f4d0a49df/types/transaction.go#L190)):*
> ```
> interface{}
> ```

Why not use type safe for `FirstTxStatus`?
___
*[types/transaction.go, line 194 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/82#-MbeZaYf0t5L5625ElLI:-MbeZaYf0t5L5625ElLJ:b-1s0pwp) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/11c9d54265b674b85f3fc241ffb92f2f4d0a49df/types/transaction.go#L194)):*
> ```
> Pending
> ```

Is it necessary to export this struct?

**Review by boqiu — CHANGES_REQUESTED** [review]
See comments in reviewable.

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/82)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @boqiu, @Pana, and @wanliqun)

___
*[types/transaction.go, line 190 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/82#-MbeZNcI5fEry1Nstc_V:-MbiobNN-Sa4RP9aCQFV:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/11c9d54265b674b85f3fc241ffb92f2f4d0a49df/types/transaction.go#L190)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> interface{}
> ```

Why not use type safe for `FirstTxStatus`?
</blockquote></details>

Done.
___
*[types/transaction.go, line 194 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/82#-MbeZaYf0t5L5625ElLI:-Mbiobtk6kG_bEIcmkl_:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/11c9d54265b674b85f3fc241ffb92f2f4d0a49df/types/transaction.go#L194)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> Pending
> ```

Is it necessary to export this struct?
</blockquote></details>

Done.

**Review by boqiu — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/82)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wanliqun)

**Pull request merged**
