### PR TITLE
add api to validate bls signature

### PR DESCRIPTION
**Pull request by boqiu**
This change is [Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/217)

### CODE REVIEW

**Review by wangdayong228 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/217)* status: all files reviewed, 2 unresolved discussions (waiting on @wangdayong228)

___
*[`types/pos/bls.go` line 56 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/217#-NYpZqhi2_EVjLcpW7As:-NYpZqhi2_EVjLcpW7At:b-a0e7ep) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/e629202cd23845525ca489718ca89eb85a147283/types/pos/bls.go#L56)):*
> ```Go
> func (info *LedgerInfoWithSignatures) Verify(committee Committee) (bool, error) {
> 	if len(info.Signatures) == 0 {
> 		panic("signatures is empty")
> ```

return an error or add a 'Must' prefix?
___
*[`types/pos/bls.go` line 142 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/217#-NYp_OJY3g_yWH3WQbNm:-NYp_OJY3g_yWH3WQbNn:b-xot1yl) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/e629202cd23845525ca489718ca89eb85a147283/types/pos/bls.go#L142)):*
> ```Go
> }
> 
> func mapToCurve(input []byte) (*bls12381.PointG2, error) {
> ```

the input is bytes, should be bytesToCurve?

**Review by boqiu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/217)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @wangdayong228)

___
*[`types/pos/bls.go` line 56 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/217#-NYpZqhi2_EVjLcpW7As:-NYpbcxnEgBETiYN9Io-:bb6un1j) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/e629202cd23845525ca489718ca89eb85a147283/types/pos/bls.go#L56)):*
<details><summary><i>Previously, wangdayong228 (dyoung) wrote…</i></summary><blockquote>

return an error or add a 'Must' prefix?
</blockquote></details>

Done
___
*[`types/pos/bls.go` line 142 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/217#-NYp_OJY3g_yWH3WQbNm:-NYpbf4dEAlfHpM88DCo:b-ny2yem) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/e629202cd23845525ca489718ca89eb85a147283/types/pos/bls.go#L142)):*
<details><summary><i>Previously, wangdayong228 (dyoung) wrote…</i></summary><blockquote>

the input is bytes, should be bytesToCurve?
</blockquote></details>

`mapToCurve` is a cryptographical term.

**Review by wangdayong228 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/217)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @boqiu)

___
*[`types/pos/bls.go` line 142 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/217#-NYp_OJY3g_yWH3WQbNm:-NYpcMSi512__gW-oCJl:b-2xzzgr) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/e629202cd23845525ca489718ca89eb85a147283/types/pos/bls.go#L142)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`mapToCurve` is a cryptographical term.
</blockquote></details>

if then, it's better to add a comment or link to describe.

**Review by wangdayong228 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/217)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @boqiu)

**Pull request merged**
