### PR TITLE
Batch request master

### PR DESCRIPTION
**Pull request by wangdayong228**
support batch request and batch send

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/124)

### CODE REVIEW

**Comment by wangdayong228** [comment]
Please test by example: https://github.com/conflux-fans/go-conflux-sdk-examples/blob/main/example_bulk

**Review by Pana — CHANGES_REQUESTED** [review]
> Reviewed 13 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/124)* status: 13 of 16 files reviewed, 4 unresolved discussions (waiting on @boqiu, @wangdayong228, and @wanliqun)

___
*[cfxclient/bulk/bulk_caller.go, line 47 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/124#-Mnj-0aI0eqpnRNouqL9:-Mnj-0aI0eqpnRNouqLA:b92stu2) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/ddb3bfac5b312c0f541d0cf335ff9d81a4456216/cfxclient/bulk/bulk_caller.go#L47)):*
> ```Go
> }
> 
> func (b *BulkCaller) Excute() ([]error, error) {
> ```

Seems the right spell is Execute 
___
*[cfxclient/bulk/bulk_caller.go, line 55 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/124#-MneZXMK27VfwumfOiiK:-MneZXML5OyFeqw26WZz:b-i5jc6i) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/ddb3bfac5b312c0f541d0cf335ff9d81a4456216/cfxclient/bulk/bulk_caller.go#L55)):*
> ```Go
> 	outHandlers map[int]*OutputHandler,
> ) ([]error, error) {
> 	fmt.Printf("outHandlers %v\n", outHandlers)
> ```

Print should be removed.
___
*[cfxclient/bulk/bulk_test.go, line 29 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/124#-MnizYea3hWWRNc92qg3:-MnizYea3hWWRNc92qg4:b-na04f0) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/ddb3bfac5b312c0f541d0cf335ff9d81a4456216/cfxclient/bulk/bulk_test.go#L29)):*
> ```Go
> 
> 	gasPrice := bulkCaller.GetGasPrice()
> 	_errors, err := bulkCaller.Excute()
> ```

Should add documentation about the Execute method, to avoid invoking it twice, or add a Clean method to bulkCaller
___
*[tools/bulk_generator.js, line 110 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/124#-Mnivg7Z-ex2NQDjP3i-:-Mnivg7_6mcmDHHixPqy:b-qxtxel) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/ddb3bfac5b312c0f541d0cf335ff9d81a4456216/tools/bulk_generator.js#L110)):*
> ```JavaScript
>         return result
>     }`]
>     const BulkCfxCaller = genBulkFile("/Users/wangdayong/myspace/mywork/go-conflux-sdk/cfxclient/rpc_cfx.go", "RpcCfxClient", missingFuncs)
> ```

The file path here should use a relative one or read from config

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/124)* status: 8 of 16 files reviewed, 4 unresolved discussions (waiting on @boqiu, @Pana, and @wanliqun)

___
*[cfxclient/bulk/bulk_caller.go, line 47 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/124#-Mnj-0aI0eqpnRNouqL9:-MnyDNpC5GXP2Enm1Bww:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/ddb3bfac5b312c0f541d0cf335ff9d81a4456216/cfxclient/bulk/bulk_caller.go#L47)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

Seems the right spell is Execute 
</blockquote></details>

Done.
___
*[cfxclient/bulk/bulk_caller.go, line 55 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/124#-MneZXMK27VfwumfOiiK:-MnyDP5j5f0sH11u7bK2:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/ddb3bfac5b312c0f541d0cf335ff9d81a4456216/cfxclient/bulk/bulk_caller.go#L55)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

Print should be removed.
</blockquote></details>

Done.
___
*[cfxclient/bulk/bulk_test.go, line 29 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/124#-MnizYea3hWWRNc92qg3:-MnyGSpTBT9bJ7q9bZYK:b-abv5xt) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/ddb3bfac5b312c0f541d0cf335ff9d81a4456216/cfxclient/bulk/bulk_test.go#L29)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

Should add documentation about the Execute method, to avoid invoking it twice, or add a Clean method to bulkCaller
</blockquote></details>

Add clear, Done.
___
*[tools/bulk_generator.js, line 110 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/124#-Mnivg7Z-ex2NQDjP3i-:-MnyHiqD5LFyuCWOSd4X:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/ddb3bfac5b312c0f541d0cf335ff9d81a4456216/tools/bulk_generator.js#L110)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

The file path here should use a relative one or read from config 
</blockquote></details>

Done.

**Review by Pana — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @boqiu and @wanliqun)

**Pull request merged**
