### PR TITLE
add `CfxMappedEVMSpaceAddress` to gen cfx mapped evm address

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/149)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/149)* status: all files reviewed, 1 unresolved discussion (waiting on @wangdayong228)

___
*[utils/addressutil/addressutil.go, line 30 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/149#-MvNXHR5B49J4dVoDtDe:-MvNXHR5B49J4dVoDtDf:bwmnvkc) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/1ce7db0deb9ccd76aafa8c13b415410fa9480718/utils/addressutil/addressutil.go#L30)):*
> ```Go
> 
> // CfxMappedEVMSpaceAddress calculate CFX space address's mapped EVM address
> func CfxMappedEVMSpaceAddress(address cfxaddress.Address) (common.Address, error) {
> ```

Why not add a member method for `cfxaddress.Address`?

**Review by Pana — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/149)* status: all files reviewed, 1 unresolved discussion (waiting on @wangdayong228)

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/149)* status: all files reviewed, 1 unresolved discussion (waiting on @wangdayong228)

___
*[types/cfxaddress/address.go, line 281 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/149#-MvNndlb1q7YdTJw3JZ4:-MvNndlcAohaaXo5ODon:b-wevftf) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/d69f21fef28e99f94082a1c6039b6e943610fb7d/types/cfxaddress/address.go#L281)):*
> ```Go
> 
> // GetMappedEVMSpaceAddress calculate CFX space address's mapped EVM address, which is the last 20 bytes of cfx address's keccak256 hash
> func (a *Address) GetMappedEVMSpaceAddress() (common.Address, error) {
> ```

Why not remove the 2nd return value `error`?

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/149)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @boqiu and @Pana)

___
*[types/cfxaddress/address.go, line 281 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/149#-MvNndlb1q7YdTJw3JZ4:-MvNsRCAD6gjbKUAk2D0:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/d69f21fef28e99f94082a1c6039b6e943610fb7d/types/cfxaddress/address.go#L281)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not remove the 2nd return value `error`?
</blockquote></details>

Done.

**Review by boqiu — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangdayong228)

**Pull request merged**
