### PR TITLE
RLP encoding/decoding support for types like block/transaction/log etc.,

### PR DESCRIPTION
**Pull request by wanliqun**
Unittests are also added

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/79)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/79)* status: all files reviewed, 2 unresolved discussions (waiting on @wanliqun)

___
*[types/block.go, line 39 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/79#-MbLXE6wA4jKab7n-KBS:-MbLXE6wA4jKab7n-KBT:bwujt9k) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/63c5fda26ff3a8c186311a9e94826f623f24646c/types/block.go#L39)):*
> ```
> wrappedBlockHeader
> ```

How about rename to `rlpEncodableBlockHeader`?
___
*[types/block.go, line 101 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/79#-MbLXTtC9GeOKX-dSo9F:-MbLXTtC9GeOKX-dSo9G:b-mt68i) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/63c5fda26ff3a8c186311a9e94826f623f24646c/types/block.go#L101)):*
> ```Go
> 
> // wrappedRLPBlockSummary wrapped block summary struct used for rlp encoding
> type wrappedRLPBlockSummary struct {
> ```

rlpEncodableBlockSummary?

**Comment by wanliqun** [comment]
> > Reviewed 8 of 8 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/79)_ status: all files reviewed, 2 unresolved discussions (waiting on @wanliqun)
> 
> _[types/block.go, line 39 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/79#-MbLXE6wA4jKab7n-KBS:-MbLXE6wA4jKab7n-KBT:bwujt9k) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/63c5fda26ff3a8c186311a9e94826f623f24646c/types/block.go#L39)):_
> 
> > ```
> > wrappedBlockHeader
> > ```
> 
> How about rename to `rlpEncodableBlockHeader`?
> 
> _[types/block.go, line 101 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/79#-MbLXTtC9GeOKX-dSo9F:-MbLXTtC9GeOKX-dSo9G:b-mt68i) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/63c5fda26ff3a8c186311a9e94826f623f24646c/types/block.go#L101)):_
> 
> > ```go
> > // wrappedRLPBlockSummary wrapped block summary struct used for rlp encoding
> > type wrappedRLPBlockSummary struct {
> > ```
> 
> rlpEncodableBlockSummary?

Done

**Review by boqiu — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/79)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wanliqun)

**Review by wangdayong228 — APPROVED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/79)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wanliqun)

**Pull request merged**
