### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by wangdayong228**
Add new Apis and documents
Use go module

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4)

### CODE REVIEW

**Comment by resodo** [comment]
___
*[account.go, line 252 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4#-M5f_YGk0goTCk4ptN6R:-M5f_YGk0goTCk4ptN6S:b-or0a1o) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/cdff3fb8bf66541b51dc86f759309c2a187a22bd/account.go#L252)):*
> ```Go
> }
> 
> // Sign signs tx by passphrase and returns the signature
> ```

sign "unsigned" tx?

**Comment by resodo** [comment]
___
*[account.go, line 252 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4#-M5f_YGk0goTCk4ptN6R:-M5faCem5Q7dyqM50Nmc:bpxouqp) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/cdff3fb8bf66541b51dc86f759309c2a187a22bd/account.go#L252)):*
<details><summary><i>Previously, resodo (Yanpei LIU) wrote…</i></summary><blockquote>

sign "unsigned" tx?
</blockquote></details>

Oh, I see, the "Sign" means Sign function. And similar things happened in other palaces.

**Comment by resodo** [comment]
___
*[client.go, line 266 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4#-M5fgEYK2PpBami_FoKZ:-M5fgEYK2PpBami_FoK_:b-kyxj4c) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/cdff3fb8bf66541b51dc86f759309c2a187a22bd/client.go#L266)):*
> ```Go
> 
> // GetTransactionsFromPool returns all pending transactions in mempool of conflux node.
> func (c *Client) GetTransactionsFromPool() (*[]types.Transaction, error) {
> ```

This function should be moved to go-conflux-sdk-for-wallet.

**Comment by resodo** [comment]
___
*[client.go, line 310 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4#-M5fgyfBAlFIlKXoKbd1:-M5fgyfC5NwcnBqw-Oq_:b-j2n503) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/cdff3fb8bf66541b51dc86f759309c2a187a22bd/client.go#L310)):*
> ```Go
> 	need = need.Add(tx.StorageLimit.ToInt(), need)
> 
> 	if balance.Cmp(need) < 0 {
> ```

The balance check looks good but unnecessary here, cause we have a sponsor mechanism.
Maybe we can have a CheckedSendTransaction API later.

**Comment by wangdayong228** [comment]
> _[client.go, line 310 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4#-M5fgyfBAlFIlKXoKbd1:-M5fgyfC5NwcnBqw-Oq_:b-j2n503) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/cdff3fb8bf66541b51dc86f759309c2a187a22bd/client.go#L310)):_
> 
> > ```go
> > 	need = need.Add(tx.StorageLimit.ToInt(), need)
> > 
> > 	if balance.Cmp(need) < 0 {
> > ```
> 
> The balance check looks good but unnecessary here, cause we have a sponsor mechanism.
> Maybe we can have a CheckedSendTransaction API later.

Could you describe the sponsor mechanism detail? 
If there are some mechanism check the balance, we can replace the logic by it.

**Comment by resodo** [comment]
___
*[client.go, line 555 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4#-M5fizeI1Fp9zCgH51nY:-M5fizeI1Fp9zCgH51nZ:bhr6gem) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/cdff3fb8bf66541b51dc86f759309c2a187a22bd/client.go#L555)):*
> ```Go
> 		}
> 
> 		if tx.Nonce == 0 {
> ```

why not "tx.Nonce == nil", what if the user just want nonce to be 0

**Comment by wangdayong228** [comment]
> _[client.go, line 555 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4#-M5fizeI1Fp9zCgH51nY:-M5fizeI1Fp9zCgH51nZ:bhr6gem) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/cdff3fb8bf66541b51dc86f759309c2a187a22bd/client.go#L555)):_
> 
> > ```go
> > 		}
> > 
> > 		if tx.Nonce == 0 {
> > ```
> 
> why not "tx.Nonce == nil", what if the user just want nonce to be 0

Grate, I will modify it.

**Comment by resodo** [comment]
___
*[types/option.go, line 27 at r3](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4#-M5qi8e78l-9vBjoti4i:-M5qi8e89b6d61bT_4ka:b1bqi3g) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/5edcbe787defdbfbc8c38ee66f8d03e5f71497ab/types/option.go#L27)):*
> ```Go
> 	Data         string       `json:"data,omitempty"`
> 	Nonce        *hexutil.Big `json:"nonce,omitempty"`
> 	StorageLimit *hexutil.Big `json:"storage_limit,omitempty"`
> ```

why the storage limit is in lower_case and gas price is in camelCase?

**Comment by resodo** [comment]
___
*[types/transaction.go, line 12 at r3](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4#-M5qifPG6GqGJzjRidrk:-M5qifPG6GqGJzjRidrl:b-k5bkx3) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/5edcbe787defdbfbc8c38ee66f8d03e5f71497ab/types/transaction.go#L12)):*
> ```Go
> 
> // TransactionCore represents a transaction without signature in Conflux
> type TransactionCore struct {
> ```

I think it's better to rename it with FullTransaction. 'core' means the essential part of something, which is not that true.

**Comment by resodo** [comment]
___
*[README.md, line 184 at r3](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4#-M5qkOVf31sd8NeUDL1E:-M5qkOVf31sd8NeUDL1F:bj1cvtg) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/5edcbe787defdbfbc8c38ee66f8d03e5f71497ab/README.md#L184)):*
> ```Markdown
> 	}
> }
> ```
> ```

pls remove the invisible ending chars

**Comment by resodo** [comment]
___
*[constants/constants.go, line 12 at r3](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4#-M5qk2my4xt8iOxtx3qz:-M5qk2mz1KhMEHJ6qe22:b-x9310o) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/5edcbe787defdbfbc8c38ee66f8d03e5f71497ab/constants/constants.go#L12)):*
> ```Go
> 
> const (
> 	MinGasprice = 1
> ```

1000000000 (1 GDrip) should be better

**Comment by resodo** [comment]
Overall, the code looks pretty good. I left some comments on the detailed problem, please fix it, thanks!

**Comment by resodo** [comment]
___
*[.gitignore, line 15 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4#-M5fWp393NywTqzczz2j:-M5fWp393NywTqzczz2k:b1nk1r3) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/cdff3fb8bf66541b51dc86f759309c2a187a22bd/.gitignore#L15)):*
> ```ignore
> 
> # Vscode related
> .vscode/
> ```

pls remove the ending space characters?

**Comment by resodo** [comment]
___
*[api.md, line 458 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4#-M5fdgX4-OE7xfKzEo4O:-M5fdgX4-OE7xfKzEo4P:b-lq8kat) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/cdff3fb8bf66541b51dc86f759309c2a187a22bd/api.md#L458)):*
> ```Markdown
> func UnmarshalRPCResult(result interface{}, v interface{}) error
> ```
> UnmarshalRPCResult unmarshals rpc result to v struct and fills in it
> ```

same as above, pls remove the ending invisible chars

**Comment by resodo** [comment]
___
*[constants/constants.go, line 13 at r4](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/4#-M5t_O63CaPGuMN4Fwdy:-M5t_O64CZncZFq5ICba:b-rd9ix6) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/eea9632c14510f6f4ad1ba093417ddee62216204/constants/constants.go#L13)):*
> ```Go
> const (
> 	// MinGasprice represents the mininum gasprice required by conflux chain when sending transactions
> 	// the value of main net is 1G drip
> ```

1 Gdrip, not 1G drip

**Comment by resodo** [comment]
:lgtm:

**Pull request merged**
