### PR TITLE
Update address checksum

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 43 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49)* status: all files reviewed, 13 unresolved discussions (waiting on @wangdayong228)

___
*[account.go, line 34 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwg-TOCnBzAQgx5J1K:-MRwg-TOCnBzAQgx5J1L:b-9x0pr7) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/account.go#L34)):*
> ```
> chainID
> ```

It is `networkID` according to the latest rust code change.
___
*[client.go, line 65 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwm8DM-G9Jd9XwzHPm:-MRwm8DM-G9Jd9XwzHPn:b611mfi) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/client.go#L65)):*
> ```Go
> //
> // the retryInterval will be set to 1 second if pass 0
> func newClientWithRetry(nodeURL string, keystorePath string, retryCount int, retryInterval time.Duration) (*Client, error) {
> ```

Why changed to `private`? Many tool uses this method to create a client instance with retry mechanism.

What's more, better not to couple `Client` with `AccountManager`. You can add an input parameter `AccountManager` in related method, or define a inherited struct to integrate `AccountManager`.
___
*[client.go, line 154 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwp8SECLwoiTq7_284:-MRwp8SECLwoiTq7_285:b3mwd12) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/client.go#L154)):*
> ```Go
> // GetNetworkID returns networkID of connecting conflux node
> func (client *Client) GetNetworkID() (uint32, error) {
> 	status, err := client.GetStatus()
> ```

why not return the field `networkID` in `Client` struct?
___
*[client_retry.go, line 75 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwpos_5IDG3noynXON:-MRwpos_5IDG3noynXOO:boc0vrm) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/client_retry.go#L75)):*
> ```Go
> }
> 
> func (r *rpcClientWithRetry) Close() {
> ```

this is a wrapper of client for retry purpose, it's unnecessary to add `Close` method.
___
*[contract_meta/internal_contract/admin_control.go, line 24 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwqPDx4cZFhebhE2bX:-MRwqPDx4cZFhebhE2bY:b12w85) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/contract_meta/internal_contract/admin_control.go#L24)):*
> ```Go
> // NewAdminControl gets the AdminControl contract object
> func NewAdminControl(client sdk.ClientOperator) (ac AdminControl, err error) {
> 	adminControlMu.Lock()
> ```

why not use `double check` pattern?
___
*[contract_meta/internal_contract/admin_control.go, line 128 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwqGfh7TwRtuV201qL:-MRwqGfh7TwRtuV201qM:bfu05ae) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/contract_meta/internal_contract/admin_control.go#L128)):*
> ```Go
> }
> 
> func getAdminControlAddress(client sdk.ClientOperator) (types.Address, error) {
> ```

why return error? it is very unfriendly for users.
___
*[types/transaction_unsigned.go, line 134 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwrHWAAOoiA7za1DQ_:-MRwrHWAAOoiA7za1DQa:b-r637ki) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/types/transaction_unsigned.go#L134)):*
> ```Go
> }
> 
> func (tx *unsignedTransactionForRlp) toUnsignedTransaction(networkID uint32) *UnsignedTransaction {
> ```

Is it possible to avoid such input parameter?

Please consider more from the user's point of view.
___
*[types/wrapped_error.go, line 21 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwrbv32SiGJ17RYjeJ:-MRwrbv48dLCfFFI_JbB:b-8h0aes) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/types/wrapped_error.go#L21)):*
> ```
> errors.Cause(err)
> ```

could void duplicated calculating.
___
*[types/cfxaddress/address.go, line 13 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwrfkV0x-0uCMQjjqG:-MRwrfkV0x-0uCMQjjqH:b-ytiur4) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/types/cfxaddress/address.go#L13)):*
> ```Go
> )
> 
> // Address ...
> ```

SDK is public to developers, please pay attention to all comments.
___
*[types/cfxaddress/address.go, line 27 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwsDQWByYg1HC6vvMM:-MRwsDQWByYg1HC6vvMN:b-jk508b) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/types/cfxaddress/address.go#L27)):*
> ```Go
> 
> // ShortString ...
> func (a Address) ShortString() string {
> ```

Better to keep consistency with other SDK.
___
*[types/cfxaddress/address.go, line 37 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwsI-wBRHBp3or5Hfp:-MRwsI-wBRHBp3or5Hfq:b-uhv4gd) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/types/cfxaddress/address.go#L37)):*
> ```Go
> 
> // NewAddressFromBase32 ...
> func NewAddressFromBase32(base32Str string) (cfxAddress Address, err error) {
> ```

In golang naming convention, `FromBase32` is enough, so that user could new an address like:`cfxaddress.FromBase32(...)`

What's more, please use go-lint to check all the code style.
___
*[types/cfxaddress/address_type.go, line 26 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRx7hfAEGdDtA9G1pez:-MRx7hfAEGdDtA9G1pf-:b-qpb2dn) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/types/cfxaddress/address_type.go#L26)):*
> ```Go
> 	AddressTypeUser     AddressType = "user"
> 	AddressTypeContract AddressType = "contract"
> 	AddressTypeNull     AddressType = "null"
> ```

Is is necessary?
___
*[types/cfxaddress/body.go, line 13 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRx7vZRAWAnyGFuTtV4:-MRx7vZRAWAnyGFuTtV5:b-e8en4s) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/types/cfxaddress/body.go#L13)):*
> ```Go
> We use the following alphabet: 0123456789abcdefghjkmnprstuvwxyz (o, i, l, q removed).
> 
> 0x00 => 0    0x08 => 8    0x10 => g    0x18 => s
> ```

charset changed?

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49)* status: all files reviewed, 13 unresolved discussions (waiting on @boqiu)

___
*[account.go, line 34 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwg-TOCnBzAQgx5J1K:-MRxUXrrCTyRzRTqL3us:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/account.go#L34)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> chainID
> ```

It is `networkID` according to the latest rust code change.
</blockquote></details>

Done.
___
*[client.go, line 65 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwm8DM-G9Jd9XwzHPm:-MRyDr2M7K0LSnJBTRfk:b-4jz321) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/client.go#L65)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why changed to `private`? Many tool uses this method to create a client instance with retry mechanism.

What's more, better not to couple `Client` with `AccountManager`. You can add an input parameter `AccountManager` in related method, or define a inherited struct to integrate `AccountManager`.
</blockquote></details>

replaced by NewClient with clientOption
___
*[client.go, line 154 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwp8SECLwoiTq7_284:-MRxUaHZ7jO9geao1Ggo:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/client.go#L154)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

why not return the field `networkID` in `Client` struct?
</blockquote></details>

Done.
___
*[client_retry.go, line 75 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwpos_5IDG3noynXON:-MRxUbjb7QkKLvVy2gMv:b4hs8lt) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/client_retry.go#L75)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

this is a wrapper of client for retry purpose, it's unnecessary to add `Close` method.
</blockquote></details>

the rpcClientWithRetry is a wrap class of rpc.Client and use same interface for convenient invoke by sdk.Client
___
*[contract_meta/internal_contract/admin_control.go, line 24 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwqPDx4cZFhebhE2bX:-MRyEH38Awftu2onsaiA:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/contract_meta/internal_contract/admin_control.go#L24)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

why not use `double check` pattern?
</blockquote></details>

Done.
___
*[contract_meta/internal_contract/admin_control.go, line 128 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwqGfh7TwRtuV201qL:-MRxXDxtDU9HASAeZa1N:b-icc3ge) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/contract_meta/internal_contract/admin_control.go#L128)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

why return error? it is very unfriendly for users.
</blockquote></details>

It's a private method and it may be error when failed to get netowrk ID
___
*[types/transaction_unsigned.go, line 134 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwrHWAAOoiA7za1DQ_:-MRxXaUW9HxFMllYIhvr:bmfqd2f) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/types/transaction_unsigned.go#L134)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Is it possible to avoid such input parameter?

Please consider more from the user's point of view.
</blockquote></details>

I have discussed with yangzhe, it's exact to set by user, because there's not context for obtaining nteworkID.
___
*[types/wrapped_error.go, line 21 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwrbv32SiGJ17RYjeJ:-MRxY4ir98oKtuvKmCP2:bhxr4zc) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/types/wrapped_error.go#L21)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> errors.Cause(err)
> ```

could void duplicated calculating.
</blockquote></details>

because it may be a wrapped json rpc error, need use Cause to unwrap the error.
___
*[types/cfxaddress/address.go, line 13 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwrfkV0x-0uCMQjjqG:-MRyEFhc5z_x_bUwFqhA:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/types/cfxaddress/address.go#L13)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

SDK is public to developers, please pay attention to all comments.
</blockquote></details>

Done.
___
*[types/cfxaddress/address.go, line 27 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwsDQWByYg1HC6vvMM:-MRxZVpWBKsZDcogNfNa:b-l3gooz) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/types/cfxaddress/address.go#L27)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Better to keep consistency with other SDK.
</blockquote></details>

Both Go and Java use class and js use string to represent address, so it may not consistency with js sdk.
___
*[types/cfxaddress/address.go, line 37 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRwsI-wBRHBp3or5Hfp:-MRxZm3AEPz3iRKbeCF4:bvwj1q) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/types/cfxaddress/address.go#L37)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

In golang naming convention, `FromBase32` is enough, so that user could new an address like:`cfxaddress.FromBase32(...)`

What's more, please use go-lint to check all the code style.
</blockquote></details>

I have tried go-lint and it doesn't has rule to check this. Changed to NewFrom...
___
*[types/cfxaddress/address_type.go, line 26 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRx7hfAEGdDtA9G1pez:-MRx_7-MD8dlxaL46E_X:b-515oil) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/types/cfxaddress/address_type.go#L26)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Is is necessary?
</blockquote></details>

Yes, it's used in many places, do you have better suggestion?
___
*[types/cfxaddress/body.go, line 13 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-MRx7vZRAWAnyGFuTtV4:-MRxaIVk9MEkqHNVf6Nn:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/87f2cab36d6f4cb969fd500bfe2a4b197436fd2a/types/cfxaddress/body.go#L13)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

charset changed?
</blockquote></details>

Done.

**Review by boqiu — APPROVED** [review]
:lgtm:

> Reviewed 27 of 27 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-:-MRyKfVU-oQvyWsZQ0u5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boqiu — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-:-MS0dqZ3288WjjHPfftG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by boqiu — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/49#-:-MS1gNjm0bTb5Vl8NDqo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
