### PR TITLE
Rpc test

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/170)

### CODE REVIEW

**Review by Pana — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/170)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @Pana and @wangdayong228)

___
*[client.go, line 536 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/170#-MzxdOlM2ZVx11gz5xlu:-MzxdOlM2ZVx11gz5xlv:burc4fh) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3f973dee285cf7d5236ff32ef192c6bb2607f6eb/client.go#L536)):*
> ```Go
> 
> 	if rpcErr, err2 := utils.ToRpcError(err); err2 == nil {
> 	return result, rpcErr
> ```

What's this update for, do we have a linter for Go?
___
*[integration_test/client_cfx_test.go, line 111 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/170#-MzxfewL6UZpPNht2y9_:-MzxfewL6UZpPNht2y9a:b-5hblok) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3f973dee285cf7d5236ff32ef192c6bb2607f6eb/integration_test/client_cfx_test.go#L111)):*
> ```Go
> 
> 	config := genCfxTestConfig()
> 	doClinetTest(t, config)
> ```

Clinet -> Client
___
*[integration_test/lib.go, line 48 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/170#-MzxhwT87bDz3-uAbRJN:-MzxhwT87bDz3-uAbRJO:bu7stb3) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3f973dee285cf7d5236ff32ef192c6bb2607f6eb/integration_test/lib.go#L48)):*
> ```Go
> 		}
> 
> 		subExamp := subExamps[0]
> ```

Seems only the first case is tested, what about others ?
___
*[types/cfxaddress/address.go, line 33 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/170#-Mzxdx3R7ETYc9OXK1ds:-Mzxdx3R7ETYc9OXK1dt:bo1r8qa) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3f973dee285cf7d5236ff32ef192c6bb2607f6eb/types/cfxaddress/address.go#L33)):*
> ```Go
> }
> 
> // TODO: Add env variable to control whether to use verbose address or short address
> ```

Seems this TODO can be removed right ?

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/170)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @Pana)

___
*[client.go, line 536 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/170#-MzxdOlM2ZVx11gz5xlu:-Mzxmp7ZCnBENEULK3Pf:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3f973dee285cf7d5236ff32ef192c6bb2607f6eb/client.go#L536)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

What's this update for, do we have a linter for Go?
</blockquote></details>

Done.
___
*[integration_test/client_cfx_test.go, line 111 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/170#-MzxfewL6UZpPNht2y9_:-MzxmqHL7MuD3E_klgNe:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3f973dee285cf7d5236ff32ef192c6bb2607f6eb/integration_test/client_cfx_test.go#L111)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

Clinet -> Client
</blockquote></details>

Done.
___
*[integration_test/lib.go, line 48 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/170#-MzxhwT87bDz3-uAbRJN:-MzxmmwoCBOlPMCeDyLk:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3f973dee285cf7d5236ff32ef192c6bb2607f6eb/integration_test/lib.go#L48)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

Seems only the first case is tested, what about others ?
</blockquote></details>

Done.
___
*[types/cfxaddress/address.go, line 33 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/170#-Mzxdx3R7ETYc9OXK1ds:-Mzxmo8R8JTf5QpbFvlk:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3f973dee285cf7d5236ff32ef192c6bb2607f6eb/types/cfxaddress/address.go#L33)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

Seems this TODO can be removed right ?
</blockquote></details>

Done.

**Review by Pana — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangdayong228)

**Review by Pana — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangdayong228)

**Pull request merged**
