### PR TITLE
Unmarshal logfilter according to full node struct

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/50)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/50)* status: all files reviewed, 2 unresolved discussions (waiting on @Pana and @wangdayong228)

___
*[client.go, line 163 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/50#-MS73LH83cWQlI6V8b3_:-MS73LH83cWQlI6V8b3a:buu1sk1) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/28c32b8815a8dbe51922de238d16ab917f6ce853/client.go#L163)):*
> ```Go
> 		return 0, errors.Wrap(err, "failed to get status")
> 	}
> 	if status.NetworkID == nil {
> ```

status.NetworkID should never be nil since Rust code use `U64` type, not `Option<U64>`
___
*[utils/utils.go, line 74 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/50#-MS73m6Z6_xsdTdYN8qS:-MS73m6Z6_xsdTdYN8qT:bynoppo) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/28c32b8815a8dbe51922de238d16ab917f6ce853/utils/utils.go#L74)):*
> ```
> JSONFmt
> ```

How about rename to `ToPrettyJSON`?

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/50)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @boqiu and @Pana)

___
*[client.go, line 163 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/50#-MS73LH83cWQlI6V8b3_:-MS7qdYm8x2aCoU6LrgI:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/28c32b8815a8dbe51922de238d16ab917f6ce853/client.go#L163)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

status.NetworkID should never be nil since Rust code use `U64` type, not `Option<U64>`
</blockquote></details>

Done.
___
*[utils/utils.go, line 74 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/50#-MS73m6Z6_xsdTdYN8qS:-MS7qgu55ey_ANVz7q7A:bclcoft) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/28c32b8815a8dbe51922de238d16ab917f6ce853/utils/utils.go#L74)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> JSONFmt
> ```

How about rename to `ToPrettyJSON`?
</blockquote></details>

Changed to PrettyJSON, I think ToPrettyJSON suit for class method and PrettyJSON suit for static method

**Review by boqiu — DISMISSED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/50)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Pana)

**Review by boqiu — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/50#-:-MSAuwrl5jCXwWISBMMG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Pana)

**Review by boqiu — APPROVED** [review]
> Reviewed 18 of 18 files at r4.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/50)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Pana)

**Pull request merged**
