### PR TITLE
support interneal contract

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/35)

### CODE REVIEW

**Review by Pana — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/35)* status: all files reviewed, 4 unresolved discussions (waiting on @wangdayong228)

___
*[contract_meta/internal_contract/admin_control.go, line 19 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/35#-MNTt5VhAQ0iHCocjt0_:-MNTt5Vi7tMkvBC2m7iN:b-jj0oi0) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/7092c3fd6e33a6787d6879566bbda450d3817637/contract_meta/internal_contract/admin_control.go#L19)):*
> ```Go
> func NewAdminControl(client sdk.ClientOperator) *AdminControl {
> 
> 	if adminControl == nil {
> ```

Use sync.Once to avoid concurrence ?
___
*[contract_meta/internal_contract/admin_control.go, line 49 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/35#-MNTsD7L6g82H9OWJVHE:-MNTsD7L6g82H9OWJVHF:bd4u2b6) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/7092c3fd6e33a6787d6879566bbda450d3817637/contract_meta/internal_contract/admin_control.go#L49)):*
> ```Go
> 
> func getAdminControlAbi() string {
> 	return `
> ```

Put the ABI to a json file is better ?
___
*[contract_meta/internal_contract/staking.go, line 35 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/35#-MNTtbndAs56kdjcJwK1:-MNTtbndAs56kdjcJwK2:bkhi8dx) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/7092c3fd6e33a6787d6879566bbda450d3817637/contract_meta/internal_contract/staking.go#L35)):*
> ```Go
> 	var tmp *big.Int = new(big.Int)
> 	err := ac.Call(option, &tmp, "getStakingBalance", user.ToCommonAddress())
> 	if err != nil {
> ```

could directly return ?
___
*[example/example_client/example_client, line 0 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/35#-MNRukZl8uQafTiL54rh:-MNRukZl8uQafTiL54ri:b-6deret) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/7092c3fd6e33a6787d6879566bbda450d3817637/example/example_client/example_client#L0)):*
this binary should not commit to git repo right ?

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/35)* status: all files reviewed, 4 unresolved discussions (waiting on @Pana)

___
*[contract_meta/internal_contract/admin_control.go, line 19 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/35#-MNTt5VhAQ0iHCocjt0_:-MNwT-g739Gk7zJzSlDm:bb7f2mf) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/7092c3fd6e33a6787d6879566bbda450d3817637/contract_meta/internal_contract/admin_control.go#L19)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

Use sync.Once to avoid concurrence ?
</blockquote></details>

done
___
*[contract_meta/internal_contract/admin_control.go, line 49 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/35#-MNTsD7L6g82H9OWJVHE:-MNwP_W0EKI4kDSFJfJ_:btnopu6) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/7092c3fd6e33a6787d6879566bbda450d3817637/contract_meta/internal_contract/admin_control.go#L49)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

Put the ABI to a json file is better ?
</blockquote></details>

it will make the file be a source and will lead to complex handle for it
___
*[contract_meta/internal_contract/staking.go, line 35 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/35#-MNTtbndAs56kdjcJwK1:-MNwOpfgCI1_5nYOZ4zm:bo9aouf) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/7092c3fd6e33a6787d6879566bbda450d3817637/contract_meta/internal_contract/staking.go#L35)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

could directly return ?
</blockquote></details>

because tmp is not nil , so it's better to return according to err value.
___
*[example/example_client/example_client, line  at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/35#-MNRukZl8uQafTiL54rh:-MNwPTDY9txXt_4yLpJX:b-kk3ut2) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/7092c3fd6e33a6787d6879566bbda450d3817637/example/example_client/example_client#L)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

this binary should not commit to git repo right ?
</blockquote></details>

solved

**Review by Pana — COMMENTED** [review]
> Reviewed 12 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/35)* status: all files reviewed, 4 unresolved discussions (waiting on @Pana)

**Review by Pana — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/35)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
