### PR TITLE
add missing rpcs

### PR DESCRIPTION
**Pull request by wangdayong228**
add missing rpcs
rpcClientWithRetry return if rpc json error occured

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21)* status: all files reviewed, 4 unresolved discussions (waiting on @wangdayong228)

___
*[client.go, line 94 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21#-MFZyfASD0Rx4anqCWJ9:-MFZyfAT-2zgTphNLQas:b-8yl78m) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/a82adf0f8339823976f38eb3da167a819c06b061/client.go#L94)):*
> ```Go
> 
> 		remain--
> 		fmt.Printf("remain retry count: %v\n", remain)
> ```

SDK should not print out any messages, instead, use logger with proper log level.

Or, return the retry count.
___
*[client.go, line 1035 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21#-MFZzCrECsPzChwxwASt:-MFZzCrECsPzChwxwASu:bfpzpg2) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/a82adf0f8339823976f38eb3da167a819c06b061/client.go#L1035)):*
> ```Go
> 
> // GetAdmin returns admin of the given contract
> func (client *Client) GetAdmin(account types.Address, epoch *types.Epoch) (admin types.Address, err error) {
> ```

1. Better to rename the 1st parameter `account` to `contract`.
2. The 2nd parameter `epoch` should be optional.
___
*[client.go, line 1041 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21#-MF_-GVW2qVk6Jm2Vj3T:-MF_-GVW2qVk6Jm2Vj3U:b-8xmtdm) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/a82adf0f8339823976f38eb3da167a819c06b061/client.go#L1041)):*
> ```Go
> 
> // GetSponsorInfo returns sponsor information of the given contract
> func (client *Client) GetSponsorInfo(contractAddress types.Address, epoch *types.Epoch) (sponsor types.SponsorInfo, err error) {
> ```

Again, `epoch` should be optional.
___
*[example/context/utils.go, line 26 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21#-MF_0lYj9S37sHFD6KHX:-MF_0lYj9S37sHFD6KHY:baup3lb) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/a82adf0f8339823976f38eb3da167a819c06b061/example/context/utils.go#L26)):*
> ```Go
> }
> 
> func WaitPacked(client *sdk.Client, txhash types.Hash) *types.Transaction {
> ```

This is a very helpful util, why not move it to Client?

BTW, strongly recommend to add method WaitForReceipt, not WaitForPacked.

**Comment by wangdayong228** [comment]
> > Reviewed 21 of 21 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21)_ status: all files reviewed, 4 unresolved discussions (waiting on @wangdayong228)
> 
> _[client.go, line 94 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21#-MFZyfASD0Rx4anqCWJ9:-MFZyfAT-2zgTphNLQas:b-8yl78m) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/a82adf0f8339823976f38eb3da167a819c06b061/client.go#L94)):_
> 
> > ```go
> > 		remain--
> > 		fmt.Printf("remain retry count: %v\n", remain)
> > ```
> 
> SDK should not print out any messages, instead, use logger with proper log level.
> 
> Or, return the retry count.
> 
> _[client.go, line 1035 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21#-MFZzCrECsPzChwxwASt:-MFZzCrECsPzChwxwASu:bfpzpg2) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/a82adf0f8339823976f38eb3da167a819c06b061/client.go#L1035)):_
> 
> > ```go
> > // GetAdmin returns admin of the given contract
> > func (client *Client) GetAdmin(account types.Address, epoch *types.Epoch) (admin types.Address, err error) {
> > ```
> 
> 1. Better to rename the 1st parameter `account` to `contract`.
> 2. The 2nd parameter `epoch` should be optional.
> 
> _[client.go, line 1041 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21#-MF_-GVW2qVk6Jm2Vj3T:-MF_-GVW2qVk6Jm2Vj3U:b-8xmtdm) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/a82adf0f8339823976f38eb3da167a819c06b061/client.go#L1041)):_
> 
> > ```go
> > // GetSponsorInfo returns sponsor information of the given contract
> > func (client *Client) GetSponsorInfo(contractAddress types.Address, epoch *types.Epoch) (sponsor types.SponsorInfo, err error) {
> > ```
> 
> Again, `epoch` should be optional.
> 
> _[example/context/utils.go, line 26 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21#-MF_0lYj9S37sHFD6KHX:-MF_0lYj9S37sHFD6KHY:baup3lb) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/a82adf0f8339823976f38eb3da167a819c06b061/example/context/utils.go#L26)):_
> 
> > ```go
> > }
> > 
> > func WaitPacked(client *sdk.Client, txhash types.Hash) *types.Transaction {
> > ```
> 
> This is a very helpful util, why not move it to Client?
> 
> BTW, strongly recommend to add method WaitForReceipt, not WaitForPacked.

Updated

Setting the epoch optional by "..." is ambiguous, it also means could pass more than one epoch. I advise to stay the epoch param currently and update it on future after we discussed a better solution.

**Comment by wangdayong228** [comment]
updated epoch to optional

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21)* status: all files reviewed, 5 unresolved discussions (waiting on @wangdayong228)

___
*[client.go, line 1149 at r3](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21#-MFeCYJACiRydb_29a2R:-MFeCYJACiRydb_29a2S:byf93wy) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/98863041a17ccbcbe84d88430a2584c7c5ecfcbe/client.go#L1149)):*
> ```Go
> // WaitForTransationBePacked returns transaction when it is packed
> func (client *Client) WaitForTransationBePacked(txhash types.Hash) *types.Transaction {
> 	fmt.Printf("wait for transaction %v be packed\n", txhash)
> ```

don't print out message in sdk
___
*[client.go, line 1152 at r3](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21#-MFeCy_tCQOG79PDOaee:-MFeCy_tCQOG79PDOaef:b6c098y) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/98863041a17ccbcbe84d88430a2584c7c5ecfcbe/client.go#L1152)):*
> ```Go
> 	var tx *types.Transaction
> 	for {
> 		time.Sleep(time.Duration(1) * time.Second)
> ```

parameterize the sleep interval?
___
*[client.go, line 1156 at r3](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21#-MFeCeuZ3_cD7rwiHHuF:-MFeCeuZ3_cD7rwiHHuG:bhbujha) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/98863041a17ccbcbe84d88430a2584c7c5ecfcbe/client.go#L1156)):*
> ```Go
> 		tx, err = client.GetTransactionByHash(txhash)
> 		if err != nil {
> 			panic(err)
> ```

panic is too serious, why not return error?
___
*[client.go, line 1169 at r3](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21#-MFeCtmZ6Z7Gl8_pouPC:-MFeCtm_5amD1dFSGccC:b7gfbcd) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/98863041a17ccbcbe84d88430a2584c7c5ecfcbe/client.go#L1169)):*
> ```Go
> // WaitForTransationReceipt waits for transaction receipt valid
> func (client *Client) WaitForTransationReceipt(txhash types.Hash) *types.TransactionReceipt {
> 	fmt.Printf("wait for transaction %v be packed\n", txhash)
> ```

don't print out message
___
*[client.go, line 1176 at r3](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21#-MFeD16oAq30I97k9QQS:-MFeD16oAq30I97k9QQT:b-w4q3vi) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/98863041a17ccbcbe84d88430a2584c7c5ecfcbe/client.go#L1176)):*
> ```Go
> 		txReceipt, err = client.GetTransactionReceipt(txhash)
> 		if err != nil {
> 			panic(err)
> ```

don't panic

**Comment by wangdayong228** [comment]
updated

**Review by boqiu — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/21)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by wangdayong228** [comment]
3q!

**Pull request merged**
