### PR TITLE
Update trace

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/142)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/142)* status: all files reviewed, 2 unresolved discussions (waiting on @wangdayong228)

___
*[types/rpc.go, line 48 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/142#-MshrRMuAvrkXMybrO7V:-MshrRMuAvrkXMybrO7W:b-y8j859) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/43ad3e602ea3051219508819bc2506734b7645ee/types/rpc.go#L48)):*
> ```Go
> type EpochPosReward struct {
> 	PowEpochHash   Hash        `json:"powEpochHash"`
> 	AccountRewards []PosReward `json:"accountRewards"`
> ```

Better to use type `[]*PosReward` to avoid value copy when iterate the slice.
___
*[types/trace.go, line 24 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/142#-MshrstI92E_91onb2VD:-MshrstI92E_91onb2VE:b-9288d2) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/43ad3e602ea3051219508819bc2506734b7645ee/types/trace.go#L24)):*
> ```Go
> 	CREATE_TYPE                    TraceType = "create"
> 	CREATE_RESULT_TYPE             TraceType = "create_result"
> 	INTERNAL_TRANSFER_ACTIION_TYPE TraceType = "internal_transfer_action"
> ```

Generally, golang use camel style for const varibales. On the other hand, better to use `CallType` as prefix for above values, e.g. `CallTypeCall`, `CallTypeCreate`.

**Comment by wangdayong228** [comment]
> > Reviewed 8 of 8 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/142)_ status: all files reviewed, 2 unresolved discussions (waiting on @wangdayong228)
> 
> _[types/rpc.go, line 48 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/142#-MshrRMuAvrkXMybrO7V:-MshrRMuAvrkXMybrO7W:b-y8j859) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/43ad3e602ea3051219508819bc2506734b7645ee/types/rpc.go#L48)):_
> 
> > ```go
> > type EpochPosReward struct {
> > 	PowEpochHash   Hash        `json:"powEpochHash"`
> > 	AccountRewards []PosReward `json:"accountRewards"`
> > ```
> 
> Better to use type `[]*PosReward` to avoid value copy when iterating the slice.
> 
In SDK, if the type is ptr or value is according to if it could be nil in the conflux-rust rpc struct, I think you could iterator slice like this to avoid copy value 
```go
for i , _:=range epochPosReward.AccountRewards{
    v:=&epochPosReward.AccountRewards[i]
    //TODO: business logic
}
```

**Review by wanliqun — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/142)* status: all files reviewed, 2 unresolved discussions (waiting on @boqiu)

**Review by boqiu — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangdayong228)

**Pull request merged**
