### PR TITLE
fix mismatched when get account by address

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/55)

### CODE REVIEW

**Review by Pana — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/55)* status: all files reviewed, 1 unresolved discussion (waiting on @wangdayong228)

___
*[account.go, line 58 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/55#-MUfuM6eCNJPEVdgLXC3:-MUfuM6eCNJPEVdgLXC4:bhgb6p6) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/e986e3973d31e126f746eedf21af5b945046a70e/account.go#L58)):*
> ```Go
> 
> 	for k, v := range am.cfxAddressDic {
> 		fmt.Printf("addr: %v account: %x\n", k, v.Address)
> ```

Is this debug code ?

**Review by Pana — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/55)* status: all files reviewed, 1 unresolved discussion (waiting on @wangdayong228)

**Review by wangdayong228 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/55#-:-MUfwykl6fXrFM-uthQf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Pana)

___
*[account.go, line 58 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/55#-MUfuM6eCNJPEVdgLXC3:-MUfwugVEEGhRd3D-Bpp:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/e986e3973d31e126f746eedf21af5b945046a70e/account.go#L58)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

Is this debug code ?
</blockquote></details>

Done.

**Review by Pana — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/55)* status: all files reviewed, 1 unresolved discussion (waiting on @Pana)

**Review by Pana — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/55)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pana — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangdayong228)

**Pull request merged**
