### PR TITLE
Update rpc 222to224

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205)

### CODE REVIEW

**Review by wanliqun — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205)* status: all files reviewed, 7 unresolved discussions (waiting on @wangdayong228)

___
*[`client.go` line 44 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-NVTikg9CgJq3m-Dhnqn:-NVTikg9CgJq3m-Dhnqo:b-8pwj83) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/7e6e0120d9adcc4de127069706b9a832f80399d8/client.go#L44)):*
> ```Go
> 	option    ClientOption
> 
> 	RpcTraceClient
> ```

why embed  `RpcTraceClient`? any diff from `RpcPosClient`, `RpcTxpoolClient` or 'RpcDebugClient`?
___
*[`interface.go` line 116 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-NVXJz469la9CydRxxXN:-NVXJz474McUyiCIsttK:bk6qz2k) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/7e6e0120d9adcc4de127069706b9a832f80399d8/interface.go#L116)):*
> ```Go
> 
> 	GetEpochReceipts(epoch types.EpochOrBlockHash) (receipts [][]types.TransactionReceipt, err error)
> 	GetEpochReceiptsByPivotBlockHash(hash types.Hash) (receipts [][]types.TransactionReceipt, err error)
> ```

Seems these two methods are already declared in `RpcDebug`  interface?



_Code quote:_
```Go
	GetEpochReceipts(epoch types.EpochOrBlockHash) (receipts [][]types.TransactionReceipt, err error)
	GetEpochReceiptsByPivotBlockHash(hash types.Hash) (receipts [][]types.TransactionReceipt, err error)
```
___
*[`interface.go` line 170 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-NVXKRjT7p4uWLRxBrvV:-NVXKRjUCYGBKMeGTlXN:b-mh2w5g) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/7e6e0120d9adcc4de127069706b9a832f80399d8/interface.go#L170)):*
> ```Go
> 	GetEpochReceipts(epoch types.EpochOrBlockHash) (receipts [][]types.TransactionReceipt, err error)
> 	GetEpochReceiptsByPivotBlockHash(hash types.Hash) (receipts [][]types.TransactionReceipt, err error)
> }
> ```

New added debug RPC methods manifested in th `RpcDebug` interface?
```
func (c *RpcDebugClient) GetTransactionsByEpoch(epoch types.Epoch) (wrapTransactions []types.WrapTransaction, err error)
func (c *RpcDebugClient) GetTransactionsByBlock(hash types.Hash) (wrapTransactions []types.WrapTransaction, err error)
```
___
*[`types/epoch.go` line 71 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-NVXL9Ea6qeAZLHJKuNY:-NVXL9Ea6qeAZLHJKuNZ:b-dz0lap) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/7e6e0120d9adcc4de127069706b9a832f80399d8/types/epoch.go#L71)):*
> ```Go
> }
> 
> // @depercated
> ```

If this is deprecated, please add some comment to state an alterative.
___
*[`types/epoch.go` line 233 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-NVXLotw82-2hTOP7Ccx:-NVXLotw82-2hTOP7Ccy:b-1t4xry) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/7e6e0120d9adcc4de127069706b9a832f80399d8/types/epoch.go#L233)):*
> ```Go
> 		e.RequirePivot = val.RequirePivot
> 		return nil
> 	}
> ```

recommend to fail fast, so that these codes are no need to embeded.



_Code quote:_
```Go
	if err == nil {
		if val.EpochNumber != nil && val.BlockHash != nil {
			return fmt.Errorf("cannot specify both BlockHash and EpochNumber, choose one or the other")
		}
		if val.EpochNumber != nil && val.RequirePivot {
			return fmt.Errorf("cannot specify both EpochNumber and RequirePivot, choose one or the other")
		}
		if val.EpochNumber != nil {
			e.epochNumber = val.EpochNumber
			return nil
		}
		e.BlockHash = val.BlockHash
		e.RequirePivot = val.RequirePivot
		return nil
	}
```
___
*[`types/epoch.go` line 277 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-NVXKxlV7pzYId3k3D3z:-NVXKxlV7pzYId3k3D4-:bam03qy) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/7e6e0120d9adcc4de127069706b9a832f80399d8/types/epoch.go#L277)):*
> ```Go
> }
> 
> // NewEpochWithBlockHash creates an instance of Epoch with specified epoch.
> ```

wrong method name for comment
___
*[`types/epoch.go` line 285 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-NVXL-wQCWWsFLjLsgYQ:-NVXL-wQCWWsFLjLsgYR:bam03qy) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/7e6e0120d9adcc4de127069706b9a832f80399d8/types/epoch.go#L285)):*
> ```Go
> }
> 
> // NewEpochWithBlockHash creates an instance of Epoch with specified block hash.
> ```

wrong method name for comment

**Review by wanliqun — COMMENTED** [review]
Discussing

> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-:-NVXNzov7HnobjcG3BCn:bl40lwn)* status: all files reviewed, 7 unresolved discussions (waiting on @wangdayong228)

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205)* status: 7 of 14 files reviewed, 7 unresolved discussions (waiting on @wanliqun)

___
*[`client.go` line 44 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-NVTikg9CgJq3m-Dhnqn:-NW5dlzeA1sVzuKRZxRi:bq14nrc) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/7e6e0120d9adcc4de127069706b9a832f80399d8/client.go#L44)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

why embed  `RpcTraceClient`? any diff from `RpcPosClient`, `RpcTxpoolClient` or 'RpcDebugClient`?
</blockquote></details>

for compatible with the previous version
___
*[`interface.go` line 116 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-NVXJz469la9CydRxxXN:-NW5eMRs3d-1zWi_1yPY:b-z7y8h5) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/7e6e0120d9adcc4de127069706b9a832f80399d8/interface.go#L116)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Seems these two methods are already declared in `RpcDebug`  interface?
</blockquote></details>

also for compatible with the previous version
___
*[`interface.go` line 170 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-NVXKRjT7p4uWLRxBrvV:-NW5iueZ1x9BvVzMrECj:bv8rk9u) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/7e6e0120d9adcc4de127069706b9a832f80399d8/interface.go#L170)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

New added debug RPC methods manifested in th `RpcDebug` interface?
```
func (c *RpcDebugClient) GetTransactionsByEpoch(epoch types.Epoch) (wrapTransactions []types.WrapTransaction, err error)
func (c *RpcDebugClient) GetTransactionsByBlock(hash types.Hash) (wrapTransactions []types.WrapTransaction, err error)
```
</blockquote></details>

`
GetTransactionsByEpoch(epoch types.Epoch)
` changed the parameter
___
*[`types/epoch.go` line 71 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-NVXL9Ea6qeAZLHJKuNY:-NW5etoGCPjQmL2tCBMC:b-896fix) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/7e6e0120d9adcc4de127069706b9a832f80399d8/types/epoch.go#L71)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

If this is deprecated, please add some comment to state an alterative.
</blockquote></details>

Done.
___
*[`types/epoch.go` line 233 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-NVXLotw82-2hTOP7Ccx:-NW5fNaY97MMaQuXCqAj:b-896fix) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/7e6e0120d9adcc4de127069706b9a832f80399d8/types/epoch.go#L233)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

recommend to fail fast, so that these codes are no need to embeded.
</blockquote></details>

Done.
___
*[`types/epoch.go` line 277 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-NVXKxlV7pzYId3k3D3z:-NW5fX4L77usg3dsnDwN:b-896fix) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/7e6e0120d9adcc4de127069706b9a832f80399d8/types/epoch.go#L277)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

wrong method name for comment
</blockquote></details>

Done.
___
*[`types/epoch.go` line 285 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-NVXL-wQCWWsFLjLsgYQ:-NW5fYmb9iBXFhOydbHn:b-896fix) ([raw file](https://github.com/Conflux-Chain/go-conflux-sdk/blob/7e6e0120d9adcc4de127069706b9a832f80399d8/types/epoch.go#L285)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

wrong method name for comment
</blockquote></details>

Done.

**Review by wanliqun — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205#-:-NW67Q4JB_tWa_qhPYhw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangdayong228)

**Review by boqiu — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/205)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangdayong228)

**Pull request merged**
