### PR TITLE
Handle errorcode

### PR DESCRIPTION
**Pull request by wangdayong228**
add error code for full node business error

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90)* status: all files reviewed, 5 unresolved discussions (waiting on @Pana, @wangdayong228, and @wanliqun)

___
*[client.go, line 811 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90#-McrNXeC7uAytnvKQPfT:-McrNXeC7uAytnvKQPfU:b-5j5n8y) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3015074a9e70a506bfd9fb6a56095014709d194d/client.go#L811)):*
> ```Go
> func (client *Client) GetEpochReceipts(epoch types.Epoch) (receipts [][]types.TransactionReceipt, err error) {
> 	err = client.wrappedCallRPC(&receipts, "cfx_getEpochReceipts", epoch)
> 	if sdkErrors.IsPivotSwitch(err) {
> ```

How about to extract a method in `sdkErrors` to wrap the rpc error?
___
*[types/cfxaddress/address.go, line 380 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90#-McrNyLV9W0QOjensVqs:-McrNyLV9W0QOjensVqt:b-t7iafu) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3015074a9e70a506bfd9fb6a56095014709d194d/types/cfxaddress/address.go#L380)):*
> ```Go
> 
> 	if len(data) <= 1 {
> 		return errors.New(fmt.Sprintf("data length must be large than 1, but get %v", string(data)))
> ```

Is it consistent with Rust code?
___
*[types/errors/errors.go, line 28 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90#-McrOMiT9CedKQdar7AD:-McrOMiT9CedKQdar7AE:bv14ap7) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3015074a9e70a506bfd9fb6a56095014709d194d/types/errors/errors.go#L28)):*
> ```Go
> }
> 
> type BusinessError struct {
> ```

I cannot find the usage of the `BusinessError`, is it necessary?

Actually, I don't think SDK has any business error.
___
*[types/errors/errors.go, line 45 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90#-McrOlMM0vB8CsMl486f:-McrOlMM0vB8CsMl486g:b-vpy80w) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3015074a9e70a506bfd9fb6a56095014709d194d/types/errors/errors.go#L45)):*
> ```Go
> 		errStr := strings.ToLower(err.Error())
> 		// pivot hash assumption failed, must be pivot switched
> 		return strings.Contains(errStr, "pivot assumption failed") || strings.Contains(errStr, "block not found")
> ```

Why not define 2 errors, one is PivotAssumptionError, and another is BlockNotFound or NotFoundError.

Actually, I think the SDK errors should keep consistent with full node.
___
*[utils/utils.go, line 73 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90#-McrPmV3DhPDgJGWmhnM:-McrPmV3DhPDgJGWmhnN:b-mtbvp5) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3015074a9e70a506bfd9fb6a56095014709d194d/utils/utils.go#L73)):*
> ```Go
> 		fmt.Printf("%+v\n", err)
> 		fmt.Println()
> 		panic(err.Error())
> ```

Strongly recommend to avoid `fmt.Println` in SDK, instead, you could panic with error message as input parameter.

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90)* status: 6 of 12 files reviewed, 5 unresolved discussions (waiting on @boqiu, @Pana, and @wanliqun)

___
*[client.go, line 811 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90#-McrNXeC7uAytnvKQPfT:-Md1Rzpg0zy3FjNJmRbe:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3015074a9e70a506bfd9fb6a56095014709d194d/client.go#L811)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about to extract a method in `sdkErrors` to wrap the rpc error?
</blockquote></details>

Done.
___
*[types/cfxaddress/address.go, line 380 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90#-McrNyLV9W0QOjensVqs:-Md1S4pKB2DWPJl6JtbR:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3015074a9e70a506bfd9fb6a56095014709d194d/types/cfxaddress/address.go#L380)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Is it consistent with Rust code?
</blockquote></details>

Done.
___
*[types/errors/errors.go, line 28 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90#-McrOMiT9CedKQdar7AD:-Md1YZxoEvPyg45V7-ef:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3015074a9e70a506bfd9fb6a56095014709d194d/types/errors/errors.go#L28)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

I cannot find the usage of the `BusinessError`, is it necessary?

Actually, I don't think SDK has any business error.
</blockquote></details>

Done.
___
*[types/errors/errors.go, line 45 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90#-McrOlMM0vB8CsMl486f:-Md1YdAF4Rz-RdwWcooF:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3015074a9e70a506bfd9fb6a56095014709d194d/types/errors/errors.go#L45)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not define 2 errors, one is PivotAssumptionError, and another is BlockNotFound or NotFoundError.

Actually, I think the SDK errors should keep consistent with full node.
</blockquote></details>

Done.
___
*[utils/utils.go, line 73 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90#-McrPmV3DhPDgJGWmhnM:-Md1StCz6ODreOlJbkNT:b1ujevx) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3015074a9e70a506bfd9fb6a56095014709d194d/utils/utils.go#L73)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Strongly recommend to avoid `fmt.Println` in SDK, instead, you could panic with error message as input parameter.
</blockquote></details>

It's only used for user, does not use in SDK API

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90)* status: all files reviewed, 2 unresolved discussions (waiting on @Pana, @wangdayong228, and @wanliqun)

___
*[types/errors/errors.go, line 43 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90#-Md1cLSF42vIa-CSFYcT:-Md1cLSF42vIa-CSFYcU:bor7u10) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3862242df0d117ffb1389fa6709ec936f23c142d/types/errors/errors.go#L43)):*
> ```Go
> // DetectErrorCode detect error code according to string of err.Error(), ok indicate accroding errorcode is found
> func DetectErrorCode(err error) (ok bool, code ErrorCode) {
> 	if err != nil {
> ```

Why not return `false, 0` when err is nil, so as to avoid unnecessary embedded block.
___
*[utils/utils.go, line 73 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90#-McrPmV3DhPDgJGWmhnM:-Md1bzuN8KVlHKJtDig4:b-93t4i5) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3015074a9e70a506bfd9fb6a56095014709d194d/utils/utils.go#L73)):*
<details><summary><i>Previously, wangdayong228 wrote…</i></summary><blockquote>

It's only used for user, does not use in SDK API
</blockquote></details>

Firstly, SDK must not use `fmt.Println`. As for this method, `panic` will output the error message properly, you need not to print the error twice.

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @boqiu, @Pana, and @wanliqun)

___
*[types/errors/errors.go, line 43 at r2](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90#-Md1cLSF42vIa-CSFYcT:-Md1eJ8306qAfL4nZWF1:by35pts) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3862242df0d117ffb1389fa6709ec936f23c142d/types/errors/errors.go#L43)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not return `false, 0` when err is nil, so as to avoid unnecessary embedded block.
</blockquote></details>

returned false 0 in the end
___
*[utils/utils.go, line 73 at r1](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90#-McrPmV3DhPDgJGWmhnM:-Md1ohuJ1jYf7JSmfdve:b-896fix) ([raw file](https://github.com/conflux-chain/go-conflux-sdk/blob/3015074a9e70a506bfd9fb6a56095014709d194d/utils/utils.go#L73)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Firstly, SDK must not use `fmt.Println`. As for this method, `panic` will output the error message properly, you need not to print the error twice.
</blockquote></details>

Done.

**Review by boqiu — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/90)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Pana and @wanliqun)

**Pull request merged**
